name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World 3"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          df -h
    parallel-job-Ubuntu 22.04:
    runs-on: ubuntu-22.04
    steps:
      - name: Memory 
        run: free -m

