name: Docker Build
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - name: Set up Docker
        uses: docker/setup-docker@v3
        with:
          dockerfile: Dockerfile
          
      - name: Build Docker image
        run: 'docker build -t your-username/apache-image:latest .'
